#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_regex='^(TICKET-[0-9]+: )'
error_msg="Aborting commit. Your commit message must start with a ticket number like TICKET-123:"

if ! grep -qE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi
