FROM node:20-alpine
WORKDIR /app

# Copy only the package.json to /app/src (to cache dependencies)
COPY ./src/package.json /app/src/

# Change working directory to /app/src
WORKDIR /app/src

# Installing modules
RUN yarn install --production=false

# Copy the rest of your application's code into /app/src
COPY ./src /app/src

# Change the working directory back to /app
WORKDIR /app

# Copy scripts and set permissions
COPY ./scripts /app/scripts
RUN chmod +x /app/scripts/start.sh

EXPOSE 3000

# # CMD to run the start script
# CMD ["/app/scripts/start.sh"]